# Generated by Django 3.1.4 on 2021-01-05 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
